# Generated by Django 3.2.16 on 2023-01-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
