# Generated by Django 3.2.16 on 2023-01-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_profile_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
